### ISSUE TITLE
This module should be renamed "FB Alpha - Arcade Games"

### ISSUE THREAD

**Issue by kwyxz** [libretro-thumbnails/FB_Alpha_-_Arcade_Games#4]
It currently downloads as "`FB_Alpha - Arcade Games`" and breaks consistency with the DATs. It should download as "`FB Alpha - Arcade Games`".

Not sure how to rename an entire module, leaving to @RobLoach because I don't want to break things :D

**Comment by RobLoach** [comment]
Hmm, downloads as from where?

**Comment by RobLoach** [comment]
Oh, I see https://github.com/libretro-thumbnails/libretro-thumbnails .

**Comment by kwyxz** [comment]
Downloads from a git pull, sorry it wasn't clear :)

**Comment by RobLoach** [comment]
Should be fixed now! https://github.com/libretro-thumbnails/libretro-thumbnails/commit/0c472be7e7efdbb605b0c337843fd44d555bd7de

Thanks for the heads up.
